apiVersion: v1
kind: Service
metadata:
  name: coolapi-service
  namespace: namespacelab9
  labels:
    app: canary-demo
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 3000
