apiVersion: v1
kind: Service
metadata:
  name: http-test-kustomize
  namespace: test-kustomize
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
  selector:
    app: http-test-kustomize