name: 2. Build application
on:
  workflow_dispatch:

env:
  REGISTRY_NAME: "acrlab0010"
  APP_NAME: "coolapi"
  IMAGE_VERSION: "1.0.0"

jobs:


  Build-Scan-Push: # Troisieme job "scan container image"
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login Azure Container Registry
        run: |
          docker login ${{ env.REGISTRY_NAME}}.azurecr.io --username ${{ secrets.CLIENTID}} --password ${{ secrets.CLIENTSECRET }}

      - name: Build de l'image de l'application
        run: |
          cd ./Lab_10/API/ && docker build -t ${{ env.REGISTRY_NAME}}.azurecr.io/${{ env.APP_NAME }}:${{ github.run_number }} .
          docker image ls

      - name: Scan Image
        uses: Azure/container-scan@v0 
        id: container-scan
        continue-on-error: true
        with:
          image-name: ${{ env.REGISTRY_NAME}}.azurecr.io/${{ env.APP_NAME }}:${{ github.run_number }}

