name: 2. Build application
on:
  workflow_dispatch:

jobs:

  Analyse-Code:
    runs-on: ubuntu-latest
    permissions: # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      actions: read # only required for workflows in private repositories https://github.com/github/codeql-action
      contents: read # only required for workflows in private repositories https://github.com/github/codeql-action
      security-events: write # required for all workflows https://github.com/github/codeql-action
    strategy:
      fail-fast: false # s'arrête s'il a une erreur dans la definition de la matrice
      matrix: # https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs
        language: [ 'javascript' ]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2 # https://github.com/github/codeql-action
        with:
          languages: ${{ matrix.language }} # https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1 # https://github.com/github/codeql-action

  test-unitaire: # Deuxieme job "tests unitaires"
    runs-on: ubuntu-latest 
    needs: Analyse-Code # Declenchement du Job "test-unitaire" si le job "analyze-code" s"execute sans erreur 
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x] # Matrice des versions Nodejs pour le test unitaire

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1 # https://github.com/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }} # application de la matrice

      - name: Installation des dependences
        run : |
          cd ./Lab_10/API/ && npm install

      - name: Tests unitaires
        run: |
          cd ./Lab_10/API/ && npm test