name: 3. Deploy application
on:
  workflow_dispatch:

jobs:

  Build-Manifest:
    runs-on: ubuntu-latest
    environment:
      name: Dev
      url: ${{ steps.ip-pub.outputs.service-url }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      

  


