name: 1. Deploy d'une application avec Kustomize
on:
  workflow_dispatch:


jobs:
  Deploy-App:
    runs-on: ubuntu-latest

    steps:
 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}