name: 1. Deploy d'une application avec Kustomize
on:
  workflow_dispatch:

env:
  RG_NAME: "RG-AKS-Lab-11"
  CLUSTER_NAME: "AKS-Lab-11"


jobs:
  Deploy-App:
    runs-on: ubuntu-latest

    steps:
 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ env.RG_NAME }} --name ${{ env.CLUSTER_NAME }}